name: "HCL AppScan CodeSweep"
on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
            fetch-depth: 0
      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
